import React, { createContext, useContext, useEffect, useState, ReactNode } from 'react';

export type Language = 'th' | 'en' | 'zh' | 'vi' | 'es' | 'ru' | 'ja' | 'ko' | 'id' | 'hi';

interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: LanguageInfo[] = [
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭' },
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
];

// Translation keys
type TranslationKeys = {
  // Common
  'common.loading': string;
  'common.error': string;
  'common.save': string;
  'common.cancel': string;
  'common.confirm': string;
  'common.back': string;
  'common.baht': string;
  'common.percent': string;
  'common.times': string;
  
  // Navigation
  'nav.feed': string;
  'nav.groups': string;
  'nav.create': string;
  'nav.calendar': string;
  'nav.profile': string;
  
  // Profile
  'profile.title': string;
  'profile.yourBadges': string;
  'profile.paidOnTime': string;
  'profile.debtClosed': string;
  'profile.newMember': string;
  'profile.totalAgreements': string;
  'profile.closedSuccess': string;
  'profile.notifications': string;
  'profile.privacy': string;
  'profile.badges': string;
  'profile.history': string;
  'profile.help': string;
  'profile.settings': string;
  'profile.logout': string;
  'profile.logoutSuccess': string;
  'profile.featureInDev': string;
  'profile.language': string;
  'profile.selectLanguage': string;
  
  // Friends
  'friends.title': string;
  'friends.count': string;
  'friends.searchPlaceholder': string;
  'friends.noResults': string;
  'friends.clearSearch': string;
  'friends.noFriends': string;
  'friends.addFirstHint': string;
  'friends.addFirst': string;
  'friends.addNew': string;
  'friends.name': string;
  'friends.namePlaceholder': string;
  'friends.phone': string;
  'friends.phonePlaceholder': string;
  'friends.add': string;
  'friends.nameRequired': string;
  'friends.addSuccess': string;
  'friends.deleteSuccess': string;
  'friends.updateSuccess': string;
  'friends.deleteConfirmTitle': string;
  'friends.deleteConfirmDesc': string;
  'friends.delete': string;
  
  // Create Agreement
  'create.title': string;
  'create.youAre': string;
  'create.lender': string;
  'create.borrower': string;
  'create.friendInfo': string;
  'create.friendName': string;
  'create.friendPhone': string;
  'create.loanAmount': string;
  'create.interest': string;
  'create.interestRate': string;
  'create.noInterest': string;
  'create.flatRate': string;
  'create.effectiveRate': string;
  'create.installments': string;
  'create.paymentFrequency': string;
  'create.daily': string;
  'create.weekly': string;
  'create.monthly': string;
  'create.dueDate': string;
  'create.notes': string;
  'create.paymentSummary': string;
  'create.principal': string;
  'create.interestPercent': string;
  'create.interestAmount': string;
  'create.paymentCount': string;
  'create.submitRequest': string;
  'create.calculationSummary': string;
  'create.totalInterest': string;
  'create.perInstallment': string;
  'create.compareAll': string;

  // PWA Install Prompt
  'pwa.closeLabel': string;
  'pwa.title': string;
  'pwa.description': string;
  'pwa.note': string;
  'pwa.iosHint': string;
  'pwa.iosAction': string;
  'pwa.installLabel': string;
  'pwa.installButton': string;
};

type Translations = Record<Language, TranslationKeys>;

const translations: Translations = {
  th: {
    'common.loading': 'กำลังโหลด...',
    'common.error': 'เกิดข้อผิดพลาด',
    'common.save': 'บันทึก',
    'common.cancel': 'ยกเลิก',
    'common.confirm': 'ยืนยัน',
    'common.back': 'กลับ',
    'common.baht': 'บาท',
    'common.percent': '%',
    'common.times': 'ครั้ง',
    'nav.feed': 'พัฒนาการเงิน',
    'nav.groups': 'แชร์บิล',
    'nav.create': 'สร้าง',
    'nav.calendar': 'ปฏิทินชำระ',
    'nav.profile': 'โปรไฟล์',
    'profile.title': 'โปรไฟล์',
    'profile.yourBadges': 'เหรียญของคุณ',
    'profile.paidOnTime': 'จ่ายตรงเวลา',
    'profile.debtClosed': 'ปิดหนี้สำเร็จ',
    'profile.newMember': 'สมาชิกใหม่',
    'profile.totalAgreements': 'ข้อตกลงทั้งหมด',
    'profile.closedSuccess': 'ปิดสำเร็จ',
    'profile.notifications': 'การแจ้งเตือน',
    'profile.privacy': 'ความเป็นส่วนตัว',
    'profile.badges': 'เหรียญรางวัล',
    'profile.history': 'ประวัติข้อตกลง',
    'profile.help': 'ช่วยเหลือ',
    'profile.settings': 'ตั้งค่า',
    'profile.logout': 'ออกจากระบบ',
    'profile.logoutSuccess': 'ออกจากระบบแล้ว',
    'profile.featureInDev': 'ฟีเจอร์นี้กำลังพัฒนา',
    'profile.language': 'ภาษา',
    'profile.selectLanguage': 'เลือกภาษา',
    'friends.title': 'เพื่อน',
    'friends.count': 'คน',
    'friends.searchPlaceholder': 'ค้นหาเพื่อน...',
    'friends.noResults': 'ไม่พบเพื่อนที่ค้นหา',
    'friends.clearSearch': 'ล้างการค้นหา',
    'friends.noFriends': 'ยังไม่มีเพื่อน',
    'friends.addFirstHint': 'เพิ่มเพื่อนเพื่อเริ่มแชร์บิลหรือสร้างข้อตกลง',
    'friends.addFirst': 'เพิ่มเพื่อนคนแรก',
    'friends.addNew': 'เพิ่มเพื่อนใหม่',
    'friends.name': 'ชื่อ',
    'friends.namePlaceholder': 'ชื่อเพื่อน',
    'friends.phone': 'เบอร์โทร (ไม่บังคับ)',
    'friends.phonePlaceholder': '08X-XXX-XXXX',
    'friends.add': 'เพิ่มเพื่อน',
    'friends.nameRequired': 'กรุณาใส่ชื่อเพื่อน',
    'friends.addSuccess': 'เพิ่มเพื่อนสำเร็จ',
    'friends.deleteSuccess': 'ลบเพื่อนแล้ว',
    'friends.updateSuccess': 'อัพเดทข้อมูลแล้ว',
    'friends.deleteConfirmTitle': 'ลบเพื่อน?',
    'friends.deleteConfirmDesc': 'การลบเพื่อนจะไม่ส่งผลกระทบต่อข้อตกลงหรือกลุ่มที่มีอยู่',
    'friends.delete': 'ลบ',
    'create.title': 'สร้างข้อตกลงใหม่',
    'create.youAre': 'คุณเป็น',
    'create.lender': 'ผู้ให้ยืม',
    'create.borrower': 'ผู้ยืม',
    'create.friendInfo': 'ข้อมูลเพื่อน',
    'create.friendName': 'ชื่อเพื่อน',
    'create.friendPhone': 'เบอร์โทร',
    'create.loanAmount': 'จำนวนเงิน',
    'create.interest': 'ดอกเบี้ย',
    'create.interestRate': 'อัตราดอกเบี้ย',
    'create.noInterest': 'ไม่คิดดอก',
    'create.flatRate': 'เงินต้นคงที่',
    'create.effectiveRate': 'ลดต้นลดดอก',
    'create.installments': 'จำนวนงวด',
    'create.paymentFrequency': 'ความถี่ในการชำระ',
    'create.daily': 'รายวัน',
    'create.weekly': 'รายสัปดาห์',
    'create.monthly': 'รายเดือน',
    'create.dueDate': 'วันครบกำหนด',
    'create.notes': 'หมายเหตุ',
    'create.paymentSummary': 'สรุปการชำระเงิน',
    'create.principal': 'เงินยืม',
    'create.interestPercent': '% ดอกเบี้ย',
    'create.interestAmount': 'ค่าดอกเบี้ย',
    'create.paymentCount': 'จำนวนครั้งที่ชำระ',
    'create.submitRequest': 'ส่งคำขอข้อตกลง',
    'create.calculationSummary': 'สรุปการคำนวณ',
    'create.totalInterest': 'ดอกเบี้ยรวม',
    'create.perInstallment': 'ชำระครั้งละ',
    'create.compareAll': 'เปรียบเทียบทุกแบบ',
    'pwa.closeLabel': 'ปิดคำแนะนำการติดตั้งแอป',
    'pwa.title': 'ติดตั้งแอป BOB',
    'pwa.description': 'เข้าถึงได้เร็วขึ้นจากหน้าจอหลัก และบางหน้าจะเปิดได้เร็วขึ้นจากแคชเมื่อเคยใช้งานแล้ว',
    'pwa.note': 'ข้อมูลสดและการทำรายการส่วนใหญ่ยังต้องต่อเน็ต',
    'pwa.iosHint': 'แตะปุ่มแชร์ แล้วเลือก',
    'pwa.iosAction': '"เพิ่มไปยังหน้าจอหลัก"',
    'pwa.installLabel': 'ติดตั้งแอป BOB',
    'pwa.installButton': 'ติดตั้งแอป',
  },
  en: {
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.baht': 'Baht',
    'common.percent': '%',
    'common.times': 'times',
    'nav.feed': 'Feed',
    'nav.groups': 'Groups',
    'nav.create': 'Create',
    'nav.calendar': 'Calendar',
    'nav.profile': 'Profile',
    'profile.title': 'Profile',
    'profile.yourBadges': 'Your Badges',
    'profile.paidOnTime': 'Paid on Time',
    'profile.debtClosed': 'Debt Closed',
    'profile.newMember': 'New Member',
    'profile.totalAgreements': 'Total Agreements',
    'profile.closedSuccess': 'Closed',
    'profile.notifications': 'Notifications',
    'profile.privacy': 'Privacy',
    'profile.badges': 'Badges',
    'profile.history': 'History',
    'profile.help': 'Help',
    'profile.settings': 'Settings',
    'profile.logout': 'Logout',
    'profile.logoutSuccess': 'Logged out',
    'profile.featureInDev': 'Feature in development',
    'profile.language': 'Language',
    'profile.selectLanguage': 'Select Language',
    'friends.title': 'Friends',
    'friends.count': 'friends',
    'friends.searchPlaceholder': 'Search friends...',
    'friends.noResults': 'No friends found',
    'friends.clearSearch': 'Clear search',
    'friends.noFriends': 'No friends yet',
    'friends.addFirstHint': 'Add friends to share bills or create agreements',
    'friends.addFirst': 'Add first friend',
    'friends.addNew': 'Add new friend',
    'friends.name': 'Name',
    'friends.namePlaceholder': 'Friend name',
    'friends.phone': 'Phone (optional)',
    'friends.phonePlaceholder': '08X-XXX-XXXX',
    'friends.add': 'Add friend',
    'friends.nameRequired': 'Please enter friend name',
    'friends.addSuccess': 'Friend added',
    'friends.deleteSuccess': 'Friend removed',
    'friends.updateSuccess': 'Friend updated',
    'friends.deleteConfirmTitle': 'Remove friend?',
    'friends.deleteConfirmDesc': 'This will not affect existing agreements or groups',
    'friends.delete': 'Remove',
    'create.title': 'Create Agreement',
    'create.youAre': 'You are',
    'create.lender': 'Lender',
    'create.borrower': 'Borrower',
    'create.friendInfo': 'Friend Info',
    'create.friendName': 'Friend Name',
    'create.friendPhone': 'Phone',
    'create.loanAmount': 'Amount',
    'create.interest': 'Interest',
    'create.interestRate': 'Interest Rate',
    'create.noInterest': 'No Interest',
    'create.flatRate': 'Flat Rate',
    'create.effectiveRate': 'Effective Rate',
    'create.installments': 'Installments',
    'create.paymentFrequency': 'Frequency',
    'create.daily': 'Daily',
    'create.weekly': 'Weekly',
    'create.monthly': 'Monthly',
    'create.dueDate': 'Due Date',
    'create.notes': 'Notes',
    'create.paymentSummary': 'Payment Summary',
    'create.principal': 'Principal',
    'create.interestPercent': 'Interest %',
    'create.interestAmount': 'Interest Amount',
    'create.paymentCount': 'Payment Count',
    'create.submitRequest': 'Send Agreement Request',
    'create.calculationSummary': 'Calculation Summary',
    'create.totalInterest': 'Total Interest',
    'create.perInstallment': 'Per Installment',
    'create.compareAll': 'Compare All',
    'pwa.closeLabel': 'Close install app prompt',
    'pwa.title': 'Install BOB',
    'pwa.description': 'Open it faster from your home screen, and some pages may load faster from cache after you\'ve used them.',
    'pwa.note': 'Live data and most actions still require an internet connection.',
    'pwa.iosHint': 'Tap the share button, then choose',
    'pwa.iosAction': '"Add to Home Screen"',
    'pwa.installLabel': 'Install BOB',
    'pwa.installButton': 'Install app',
  },
  zh: {
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.back': '返回',
    'common.baht': '泰铢',
    'common.percent': '%',
    'common.times': '次',
    'nav.feed': '财务动态',
    'nav.groups': '分账',
    'nav.create': '创建',
    'nav.calendar': '还款日历',
    'nav.profile': '个人资料',
    'profile.title': '个人资料',
    'profile.yourBadges': '您的徽章',
    'profile.paidOnTime': '按时付款',
    'profile.debtClosed': '债务结清',
    'profile.newMember': '新会员',
    'profile.totalAgreements': '协议总数',
    'profile.closedSuccess': '已完成',
    'profile.notifications': '通知',
    'profile.privacy': '隐私',
    'profile.badges': '徽章',
    'profile.history': '历史记录',
    'profile.help': '帮助',
    'profile.settings': '设置',
    'profile.logout': '登出',
    'profile.logoutSuccess': '已登出',
    'profile.featureInDev': '功能开发中',
    'profile.language': '语言',
    'profile.selectLanguage': '选择语言',
    'friends.title': '好友',
    'friends.count': '位好友',
    'friends.searchPlaceholder': '搜索好友...',
    'friends.noResults': '未找到好友',
    'friends.clearSearch': '清除搜索',
    'friends.noFriends': '还没有好友',
    'friends.addFirstHint': '添加好友以分账或创建协议',
    'friends.addFirst': '添加第一个好友',
    'friends.addNew': '添加新好友',
    'friends.name': '姓名',
    'friends.namePlaceholder': '好友姓名',
    'friends.phone': '电话（可选）',
    'friends.phonePlaceholder': '08X-XXX-XXXX',
    'friends.add': '添加好友',
    'friends.nameRequired': '请输入好友姓名',
    'friends.addSuccess': '好友已添加',
    'friends.deleteSuccess': '好友已删除',
    'friends.updateSuccess': '好友已更新',
    'friends.deleteConfirmTitle': '删除好友？',
    'friends.deleteConfirmDesc': '这不会影响现有的协议或群组',
    'friends.delete': '删除',
    'create.title': '创建新协议',
    'create.youAre': '您是',
    'create.lender': '出借人',
    'create.borrower': '借款人',
    'create.friendInfo': '朋友信息',
    'create.friendName': '朋友姓名',
    'create.friendPhone': '电话',
    'create.loanAmount': '金额',
    'create.interest': '利息',
    'create.interestRate': '利率',
    'create.noInterest': '无利息',
    'create.flatRate': '固定利率',
    'create.effectiveRate': '递减利率',
    'create.installments': '分期数',
    'create.paymentFrequency': '还款频率',
    'create.daily': '每日',
    'create.weekly': '每周',
    'create.monthly': '每月',
    'create.dueDate': '到期日',
    'create.notes': '备注',
    'create.paymentSummary': '还款摘要',
    'create.principal': '本金',
    'create.interestPercent': '利率%',
    'create.interestAmount': '利息金额',
    'create.paymentCount': '还款次数',
    'create.submitRequest': '发送协议请求',
    'create.calculationSummary': '计算摘要',
    'create.totalInterest': '总利息',
    'create.perInstallment': '每期金额',
    'create.compareAll': '全部比较',
    'pwa.closeLabel': '关闭安装应用提示',
    'pwa.title': '安装 BOB',
    'pwa.description': '从主屏幕更快打开，部分页面在使用后可从缓存更快加载。',
    'pwa.note': '实时数据和大多数操作仍需要网络连接。',
    'pwa.iosHint': '点击分享按钮，然后选择',
    'pwa.iosAction': '"添加到主屏幕"',
    'pwa.installLabel': '安装 BOB',
    'pwa.installButton': '安装应用',
  },
  vi: {
    'common.loading': 'Đang tải...',
    'common.error': 'Lỗi',
    'common.save': 'Lưu',
    'common.cancel': 'Hủy',
    'common.confirm': 'Xác nhận',
    'common.back': 'Quay lại',
    'common.baht': 'Baht',
    'common.percent': '%',
    'common.times': 'lần',
    'nav.feed': 'Tài chính',
    'nav.groups': 'Chia bill',
    'nav.create': 'Tạo',
    'nav.calendar': 'Lịch thanh toán',
    'nav.profile': 'Hồ sơ',
    'profile.title': 'Hồ sơ',
    'profile.yourBadges': 'Huy hiệu của bạn',
    'profile.paidOnTime': 'Trả đúng hạn',
    'profile.debtClosed': 'Đã tất toán',
    'profile.newMember': 'Thành viên mới',
    'profile.totalAgreements': 'Tổng thỏa thuận',
    'profile.closedSuccess': 'Đã hoàn thành',
    'profile.notifications': 'Thông báo',
    'profile.privacy': 'Quyền riêng tư',
    'profile.badges': 'Huy hiệu',
    'profile.history': 'Lịch sử',
    'profile.help': 'Trợ giúp',
    'profile.settings': 'Cài đặt',
    'profile.logout': 'Đăng xuất',
    'profile.logoutSuccess': 'Đã đăng xuất',
    'profile.featureInDev': 'Tính năng đang phát triển',
    'profile.language': 'Ngôn ngữ',
    'profile.selectLanguage': 'Chọn ngôn ngữ',
    'friends.title': 'Bạn bè',
    'friends.count': 'bạn',
    'friends.searchPlaceholder': 'Tìm bạn bè...',
    'friends.noResults': 'Không tìm thấy bạn bè',
    'friends.clearSearch': 'Xóa tìm kiếm',
    'friends.noFriends': 'Chưa có bạn bè',
    'friends.addFirstHint': 'Thêm bạn bè để chia bill hoặc tạo thỏa thuận',
    'friends.addFirst': 'Thêm bạn đầu tiên',
    'friends.addNew': 'Thêm bạn mới',
    'friends.name': 'Tên',
    'friends.namePlaceholder': 'Tên bạn bè',
    'friends.phone': 'Điện thoại (tùy chọn)',
    'friends.phonePlaceholder': '08X-XXX-XXXX',
    'friends.add': 'Thêm bạn',
    'friends.nameRequired': 'Vui lòng nhập tên bạn bè',
    'friends.addSuccess': 'Đã thêm bạn bè',
    'friends.deleteSuccess': 'Đã xóa bạn bè',
    'friends.updateSuccess': 'Đã cập nhật bạn bè',
    'friends.deleteConfirmTitle': 'Xóa bạn bè?',
    'friends.deleteConfirmDesc': 'Điều này không ảnh hưởng đến các thỏa thuận hoặc nhóm hiện có',
    'friends.delete': 'Xóa',
    'create.title': 'Tạo thỏa thuận mới',
    'create.youAre': 'Bạn là',
    'create.lender': 'Người cho vay',
    'create.borrower': 'Người vay',
    'create.friendInfo': 'Thông tin bạn bè',
    'create.friendName': 'Tên bạn bè',
    'create.friendPhone': 'Điện thoại',
    'create.loanAmount': 'Số tiền',
    'create.interest': 'Lãi suất',
    'create.interestRate': 'Tỷ lệ lãi suất',
    'create.noInterest': 'Không lãi',
    'create.flatRate': 'Lãi cố định',
    'create.effectiveRate': 'Lãi giảm dần',
    'create.installments': 'Số kỳ',
    'create.paymentFrequency': 'Tần suất',
    'create.daily': 'Hàng ngày',
    'create.weekly': 'Hàng tuần',
    'create.monthly': 'Hàng tháng',
    'create.dueDate': 'Ngày đến hạn',
    'create.notes': 'Ghi chú',
    'create.paymentSummary': 'Tóm tắt thanh toán',
    'create.principal': 'Gốc',
    'create.interestPercent': '% Lãi',
    'create.interestAmount': 'Tiền lãi',
    'create.paymentCount': 'Số lần trả',
    'create.submitRequest': 'Gửi yêu cầu',
    'create.calculationSummary': 'Tóm tắt tính toán',
    'create.totalInterest': 'Tổng lãi',
    'create.perInstallment': 'Mỗi kỳ',
    'create.compareAll': 'So sánh tất cả',
    'pwa.closeLabel': 'Đóng gợi ý cài đặt ứng dụng',
    'pwa.title': 'Cài đặt BOB',
    'pwa.description': 'Mở nhanh hơn từ màn hình chính, một số trang có thể tải nhanh hơn từ bộ nhớ đệm.',
    'pwa.note': 'Dữ liệu trực tiếp và hầu hết các thao tác vẫn cần kết nối internet.',
    'pwa.iosHint': 'Nhấn nút chia sẻ, sau đó chọn',
    'pwa.iosAction': '"Thêm vào màn hình chính"',
    'pwa.installLabel': 'Cài đặt BOB',
    'pwa.installButton': 'Cài đặt ứng dụng',
  },
  es: {
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.back': 'Volver',
    'common.baht': 'Baht',
    'common.percent': '%',
    'common.times': 'veces',
    'nav.feed': 'Finanzas',
    'nav.groups': 'Grupos',
    'nav.create': 'Crear',
    'nav.calendar': 'Calendario',
    'nav.profile': 'Perfil',
    'profile.title': 'Perfil',
    'profile.yourBadges': 'Tus insignias',
    'profile.paidOnTime': 'Pago puntual',
    'profile.debtClosed': 'Deuda cerrada',
    'profile.newMember': 'Nuevo miembro',
    'profile.totalAgreements': 'Total acuerdos',
    'profile.closedSuccess': 'Completados',
    'profile.notifications': 'Notificaciones',
    'profile.privacy': 'Privacidad',
    'profile.badges': 'Insignias',
    'profile.history': 'Historial',
    'profile.help': 'Ayuda',
    'profile.settings': 'Ajustes',
    'profile.logout': 'Cerrar sesión',
    'profile.logoutSuccess': 'Sesión cerrada',
    'profile.featureInDev': 'Función en desarrollo',
    'profile.language': 'Idioma',
    'profile.selectLanguage': 'Seleccionar idioma',
    'friends.title': 'Amigos',
    'friends.count': 'amigos',
    'friends.searchPlaceholder': 'Buscar amigos...',
    'friends.noResults': 'No se encontraron amigos',
    'friends.clearSearch': 'Limpiar búsqueda',
    'friends.noFriends': 'Sin amigos aún',
    'friends.addFirstHint': 'Añade amigos para dividir gastos o crear acuerdos',
    'friends.addFirst': 'Añadir primer amigo',
    'friends.addNew': 'Añadir nuevo amigo',
    'friends.name': 'Nombre',
    'friends.namePlaceholder': 'Nombre del amigo',
    'friends.phone': 'Teléfono (opcional)',
    'friends.phonePlaceholder': '08X-XXX-XXXX',
    'friends.add': 'Añadir amigo',
    'friends.nameRequired': 'Por favor ingresa el nombre',
    'friends.addSuccess': 'Amigo añadido',
    'friends.deleteSuccess': 'Amigo eliminado',
    'friends.updateSuccess': 'Amigo actualizado',
    'friends.deleteConfirmTitle': '¿Eliminar amigo?',
    'friends.deleteConfirmDesc': 'Esto no afectará los acuerdos o grupos existentes',
    'friends.delete': 'Eliminar',
    'create.title': 'Crear acuerdo',
    'create.youAre': 'Eres',
    'create.lender': 'Prestamista',
    'create.borrower': 'Prestatario',
    'create.friendInfo': 'Info del amigo',
    'create.friendName': 'Nombre',
    'create.friendPhone': 'Teléfono',
    'create.loanAmount': 'Cantidad',
    'create.interest': 'Interés',
    'create.interestRate': 'Tasa de interés',
    'create.noInterest': 'Sin interés',
    'create.flatRate': 'Tasa fija',
    'create.effectiveRate': 'Tasa efectiva',
    'create.installments': 'Cuotas',
    'create.paymentFrequency': 'Frecuencia',
    'create.daily': 'Diario',
    'create.weekly': 'Semanal',
    'create.monthly': 'Mensual',
    'create.dueDate': 'Fecha límite',
    'create.notes': 'Notas',
    'create.paymentSummary': 'Resumen de pago',
    'create.principal': 'Principal',
    'create.interestPercent': '% Interés',
    'create.interestAmount': 'Monto interés',
    'create.paymentCount': 'Núm. pagos',
    'create.submitRequest': 'Enviar solicitud',
    'create.calculationSummary': 'Resumen cálculo',
    'create.totalInterest': 'Interés total',
    'create.perInstallment': 'Por cuota',
    'create.compareAll': 'Comparar todo',
    'pwa.closeLabel': 'Cerrar aviso de instalación',
    'pwa.title': 'Instalar BOB',
    'pwa.description': 'Ábrelo más rápido desde tu pantalla de inicio, algunas páginas pueden cargarse antes desde caché.',
    'pwa.note': 'Los datos en vivo y la mayoría de acciones aún requieren conexión a internet.',
    'pwa.iosHint': 'Toca el botón compartir y elige',
    'pwa.iosAction': '"Añadir a pantalla de inicio"',
    'pwa.installLabel': 'Instalar BOB',
    'pwa.installButton': 'Instalar app',
  },
  ru: {
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.confirm': 'Подтвердить',
    'common.back': 'Назад',
    'common.baht': 'Бат',
    'common.percent': '%',
    'common.times': 'раз',
    'nav.feed': 'Финансы',
    'nav.groups': 'Группы',
    'nav.create': 'Создать',
    'nav.calendar': 'Календарь',
    'nav.profile': 'Профиль',
    'profile.title': 'Профиль',
    'profile.yourBadges': 'Ваши значки',
    'profile.paidOnTime': 'Вовремя',
    'profile.debtClosed': 'Долг закрыт',
    'profile.newMember': 'Новый член',
    'profile.totalAgreements': 'Всего соглашений',
    'profile.closedSuccess': 'Завершено',
    'profile.notifications': 'Уведомления',
    'profile.privacy': 'Конфиденциальность',
    'profile.badges': 'Значки',
    'profile.history': 'История',
    'profile.help': 'Помощь',
    'profile.settings': 'Настройки',
    'profile.logout': 'Выйти',
    'profile.logoutSuccess': 'Вы вышли',
    'profile.featureInDev': 'Функция в разработке',
    'profile.language': 'Язык',
    'profile.selectLanguage': 'Выбрать язык',
    'friends.title': 'Друзья',
    'friends.count': 'друзей',
    'friends.searchPlaceholder': 'Поиск друзей...',
    'friends.noResults': 'Друзья не найдены',
    'friends.clearSearch': 'Очистить поиск',
    'friends.noFriends': 'Пока нет друзей',
    'friends.addFirstHint': 'Добавьте друзей для разделения счетов или создания соглашений',
    'friends.addFirst': 'Добавить первого друга',
    'friends.addNew': 'Добавить нового друга',
    'friends.name': 'Имя',
    'friends.namePlaceholder': 'Имя друга',
    'friends.phone': 'Телефон (необязательно)',
    'friends.phonePlaceholder': '08X-XXX-XXXX',
    'friends.add': 'Добавить друга',
    'friends.nameRequired': 'Пожалуйста, введите имя друга',
    'friends.addSuccess': 'Друг добавлен',
    'friends.deleteSuccess': 'Друг удалён',
    'friends.updateSuccess': 'Друг обновлён',
    'friends.deleteConfirmTitle': 'Удалить друга?',
    'friends.deleteConfirmDesc': 'Это не повлияет на существующие соглашения или группы',
    'friends.delete': 'Удалить',
    'create.title': 'Создать соглашение',
    'create.youAre': 'Вы',
    'create.lender': 'Кредитор',
    'create.borrower': 'Заёмщик',
    'create.friendInfo': 'Данные друга',
    'create.friendName': 'Имя друга',
    'create.friendPhone': 'Телефон',
    'create.loanAmount': 'Сумма',
    'create.interest': 'Процент',
    'create.interestRate': 'Процентная ставка',
    'create.noInterest': 'Без процентов',
    'create.flatRate': 'Фикс. ставка',
    'create.effectiveRate': 'Эффект. ставка',
    'create.installments': 'Платежи',
    'create.paymentFrequency': 'Частота',
    'create.daily': 'Ежедневно',
    'create.weekly': 'Еженедельно',
    'create.monthly': 'Ежемесячно',
    'create.dueDate': 'Срок',
    'create.notes': 'Заметки',
    'create.paymentSummary': 'Сводка платежей',
    'create.principal': 'Основная сумма',
    'create.interestPercent': '% Процент',
    'create.interestAmount': 'Сумма процентов',
    'create.paymentCount': 'Кол-во платежей',
    'create.submitRequest': 'Отправить запрос',
    'create.calculationSummary': 'Расчёт',
    'create.totalInterest': 'Всего проценты',
    'create.perInstallment': 'За платёж',
    'create.compareAll': 'Сравнить все',
    'pwa.closeLabel': 'Закрыть подсказку установки',
    'pwa.title': 'Установить BOB',
    'pwa.description': 'Открывайте быстрее с главного экрана, некоторые страницы загружаются быстрее из кэша.',
    'pwa.note': 'Актуальные данные и большинство действий по-прежнему требуют интернета.',
    'pwa.iosHint': 'Нажмите кнопку «Поделиться», затем выберите',
    'pwa.iosAction': '"Добавить на экран «Домой»"',
    'pwa.installLabel': 'Установить BOB',
    'pwa.installButton': 'Установить',
  },
  ja: {
    'common.loading': '読み込み中...',
    'common.error': 'エラー',
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.confirm': '確認',
    'common.back': '戻る',
    'common.baht': 'バーツ',
    'common.percent': '%',
    'common.times': '回',
    'nav.feed': '財務',
    'nav.groups': 'グループ',
    'nav.create': '作成',
    'nav.calendar': 'カレンダー',
    'nav.profile': 'プロフィール',
    'profile.title': 'プロフィール',
    'profile.yourBadges': 'あなたのバッジ',
    'profile.paidOnTime': '期日通り',
    'profile.debtClosed': '完済',
    'profile.newMember': '新規メンバー',
    'profile.totalAgreements': '契約総数',
    'profile.closedSuccess': '完了',
    'profile.notifications': '通知',
    'profile.privacy': 'プライバシー',
    'profile.badges': 'バッジ',
    'profile.history': '履歴',
    'profile.help': 'ヘルプ',
    'profile.settings': '設定',
    'profile.logout': 'ログアウト',
    'profile.logoutSuccess': 'ログアウトしました',
    'profile.featureInDev': '開発中の機能',
    'profile.language': '言語',
    'profile.selectLanguage': '言語を選択',
    'friends.title': '友達',
    'friends.count': '人',
    'friends.searchPlaceholder': '友達を検索...',
    'friends.noResults': '友達が見つかりません',
    'friends.clearSearch': '検索をクリア',
    'friends.noFriends': 'まだ友達がいません',
    'friends.addFirstHint': '請求書の分割や契約の作成に友達を追加',
    'friends.addFirst': '最初の友達を追加',
    'friends.addNew': '新しい友達を追加',
    'friends.name': '名前',
    'friends.namePlaceholder': '友達の名前',
    'friends.phone': '電話（任意）',
    'friends.phonePlaceholder': '08X-XXX-XXXX',
    'friends.add': '友達を追加',
    'friends.nameRequired': '友達の名前を入力してください',
    'friends.addSuccess': '友達を追加しました',
    'friends.deleteSuccess': '友達を削除しました',
    'friends.updateSuccess': '友達を更新しました',
    'friends.deleteConfirmTitle': '友達を削除しますか？',
    'friends.deleteConfirmDesc': '既存の契約やグループには影響しません',
    'friends.delete': '削除',
    'create.title': '契約を作成',
    'create.youAre': 'あなたは',
    'create.lender': '貸し手',
    'create.borrower': '借り手',
    'create.friendInfo': '友人情報',
    'create.friendName': '友人の名前',
    'create.friendPhone': '電話番号',
    'create.loanAmount': '金額',
    'create.interest': '利息',
    'create.interestRate': '利率',
    'create.noInterest': '無利息',
    'create.flatRate': '固定金利',
    'create.effectiveRate': '実効金利',
    'create.installments': '分割数',
    'create.paymentFrequency': '頻度',
    'create.daily': '毎日',
    'create.weekly': '毎週',
    'create.monthly': '毎月',
    'create.dueDate': '期日',
    'create.notes': 'メモ',
    'create.paymentSummary': '支払い概要',
    'create.principal': '元金',
    'create.interestPercent': '% 利息',
    'create.interestAmount': '利息額',
    'create.paymentCount': '支払い回数',
    'create.submitRequest': 'リクエスト送信',
    'create.calculationSummary': '計算概要',
    'create.totalInterest': '合計利息',
    'create.perInstallment': '1回あたり',
    'create.compareAll': '全て比較',
    'pwa.closeLabel': 'アプリインストール案内を閉じる',
    'pwa.title': 'BOBをインストール',
    'pwa.description': 'ホーム画面からすばやく起動でき、一部のページはキャッシュから速く読み込めます。',
    'pwa.note': 'リアルタイムデータや多くの操作にはインターネット接続が必要です。',
    'pwa.iosHint': '共有ボタンをタップして選択',
    'pwa.iosAction': '「ホーム画面に追加」',
    'pwa.installLabel': 'BOBをインストール',
    'pwa.installButton': 'インストール',
  },
  ko: {
    'common.loading': '로딩 중...',
    'common.error': '오류',
    'common.save': '저장',
    'common.cancel': '취소',
    'common.confirm': '확인',
    'common.back': '뒤로',
    'common.baht': '바트',
    'common.percent': '%',
    'common.times': '회',
    'nav.feed': '피드',
    'nav.groups': '그룹',
    'nav.create': '생성',
    'nav.calendar': '캘린더',
    'nav.profile': '프로필',
    'profile.title': '프로필',
    'profile.yourBadges': '내 배지',
    'profile.paidOnTime': '정시 결제',
    'profile.debtClosed': '부채 완료',
    'profile.newMember': '신규 회원',
    'profile.totalAgreements': '총 계약',
    'profile.closedSuccess': '완료됨',
    'profile.notifications': '알림',
    'profile.privacy': '개인정보',
    'profile.badges': '배지',
    'profile.history': '기록',
    'profile.help': '도움말',
    'profile.settings': '설정',
    'profile.logout': '로그아웃',
    'profile.logoutSuccess': '로그아웃됨',
    'profile.featureInDev': '개발 중인 기능',
    'profile.language': '언어',
    'profile.selectLanguage': '언어 선택',
    'friends.title': '친구',
    'friends.count': '명',
    'friends.searchPlaceholder': '친구 검색...',
    'friends.noResults': '친구를 찾을 수 없습니다',
    'friends.clearSearch': '검색 지우기',
    'friends.noFriends': '아직 친구가 없습니다',
    'friends.addFirstHint': '청구서 분할 또는 계약 생성을 위해 친구를 추가하세요',
    'friends.addFirst': '첫 친구 추가',
    'friends.addNew': '새 친구 추가',
    'friends.name': '이름',
    'friends.namePlaceholder': '친구 이름',
    'friends.phone': '전화 (선택)',
    'friends.phonePlaceholder': '08X-XXX-XXXX',
    'friends.add': '친구 추가',
    'friends.nameRequired': '친구 이름을 입력하세요',
    'friends.addSuccess': '친구 추가됨',
    'friends.deleteSuccess': '친구 삭제됨',
    'friends.updateSuccess': '친구 업데이트됨',
    'friends.deleteConfirmTitle': '친구를 삭제하시겠습니까?',
    'friends.deleteConfirmDesc': '기존 계약이나 그룹에는 영향이 없습니다',
    'friends.delete': '삭제',
    'create.title': '계약 생성',
    'create.youAre': '당신은',
    'create.lender': '대출자',
    'create.borrower': '차용자',
    'create.friendInfo': '친구 정보',
    'create.friendName': '친구 이름',
    'create.friendPhone': '전화번호',
    'create.loanAmount': '금액',
    'create.interest': '이자',
    'create.interestRate': '이자율',
    'create.noInterest': '무이자',
    'create.flatRate': '고정 금리',
    'create.effectiveRate': '실효 금리',
    'create.installments': '할부',
    'create.paymentFrequency': '빈도',
    'create.daily': '매일',
    'create.weekly': '매주',
    'create.monthly': '매월',
    'create.dueDate': '마감일',
    'create.notes': '메모',
    'create.paymentSummary': '결제 요약',
    'create.principal': '원금',
    'create.interestPercent': '% 이자',
    'create.interestAmount': '이자 금액',
    'create.paymentCount': '결제 횟수',
    'create.submitRequest': '요청 보내기',
    'create.calculationSummary': '계산 요약',
    'create.totalInterest': '총 이자',
    'create.perInstallment': '회당',
    'create.compareAll': '모두 비교',
    'pwa.closeLabel': '앱 설치 안내 닫기',
    'pwa.title': 'BOB 설치',
    'pwa.description': '홈 화면에서 더 빠르게 열 수 있고, 사용 후 일부 페이지는 캐시에서 더 빠르게 로드됩니다.',
    'pwa.note': '실시간 데이터와 대부분의 작업은 여전히 인터넷 연결이 필요합니다.',
    'pwa.iosHint': '공유 버튼을 탭한 후 선택',
    'pwa.iosAction': '"홈 화면에 추가"',
    'pwa.installLabel': 'BOB 설치',
    'pwa.installButton': '앱 설치',
  },
  id: {
    'common.loading': 'Memuat...',
    'common.error': 'Kesalahan',
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.confirm': 'Konfirmasi',
    'common.back': 'Kembali',
    'common.baht': 'Baht',
    'common.percent': '%',
    'common.times': 'kali',
    'nav.feed': 'Beranda',
    'nav.groups': 'Grup',
    'nav.create': 'Buat',
    'nav.calendar': 'Kalender',
    'nav.profile': 'Profil',
    'profile.title': 'Profil',
    'profile.yourBadges': 'Lencana Anda',
    'profile.paidOnTime': 'Bayar Tepat Waktu',
    'profile.debtClosed': 'Utang Lunas',
    'profile.newMember': 'Anggota Baru',
    'profile.totalAgreements': 'Total Perjanjian',
    'profile.closedSuccess': 'Selesai',
    'profile.notifications': 'Notifikasi',
    'profile.privacy': 'Privasi',
    'profile.badges': 'Lencana',
    'profile.history': 'Riwayat',
    'profile.help': 'Bantuan',
    'profile.settings': 'Pengaturan',
    'profile.logout': 'Keluar',
    'profile.logoutSuccess': 'Sudah keluar',
    'profile.featureInDev': 'Fitur dalam pengembangan',
    'profile.language': 'Bahasa',
    'profile.selectLanguage': 'Pilih Bahasa',
    'friends.title': 'Teman',
    'friends.count': 'teman',
    'friends.searchPlaceholder': 'Cari teman...',
    'friends.noResults': 'Teman tidak ditemukan',
    'friends.clearSearch': 'Hapus pencarian',
    'friends.noFriends': 'Belum ada teman',
    'friends.addFirstHint': 'Tambah teman untuk berbagi tagihan atau membuat perjanjian',
    'friends.addFirst': 'Tambah teman pertama',
    'friends.addNew': 'Tambah teman baru',
    'friends.name': 'Nama',
    'friends.namePlaceholder': 'Nama teman',
    'friends.phone': 'Telepon (opsional)',
    'friends.phonePlaceholder': '08X-XXX-XXXX',
    'friends.add': 'Tambah teman',
    'friends.nameRequired': 'Silakan masukkan nama teman',
    'friends.addSuccess': 'Teman ditambahkan',
    'friends.deleteSuccess': 'Teman dihapus',
    'friends.updateSuccess': 'Teman diperbarui',
    'friends.deleteConfirmTitle': 'Hapus teman?',
    'friends.deleteConfirmDesc': 'Ini tidak akan mempengaruhi perjanjian atau grup yang ada',
    'friends.delete': 'Hapus',
    'create.title': 'Buat Perjanjian',
    'create.youAre': 'Anda adalah',
    'create.lender': 'Pemberi Pinjaman',
    'create.borrower': 'Peminjam',
    'create.friendInfo': 'Info Teman',
    'create.friendName': 'Nama Teman',
    'create.friendPhone': 'Telepon',
    'create.loanAmount': 'Jumlah',
    'create.interest': 'Bunga',
    'create.interestRate': 'Suku Bunga',
    'create.noInterest': 'Tanpa Bunga',
    'create.flatRate': 'Bunga Tetap',
    'create.effectiveRate': 'Bunga Efektif',
    'create.installments': 'Cicilan',
    'create.paymentFrequency': 'Frekuensi',
    'create.daily': 'Harian',
    'create.weekly': 'Mingguan',
    'create.monthly': 'Bulanan',
    'create.dueDate': 'Jatuh Tempo',
    'create.notes': 'Catatan',
    'create.paymentSummary': 'Ringkasan Pembayaran',
    'create.principal': 'Pokok',
    'create.interestPercent': '% Bunga',
    'create.interestAmount': 'Jumlah Bunga',
    'create.paymentCount': 'Jumlah Pembayaran',
    'create.submitRequest': 'Kirim Permintaan',
    'create.calculationSummary': 'Ringkasan Perhitungan',
    'create.totalInterest': 'Total Bunga',
    'create.perInstallment': 'Per Cicilan',
    'create.compareAll': 'Bandingkan Semua',
    'pwa.closeLabel': 'Tutup petunjuk instalasi aplikasi',
    'pwa.title': 'Pasang BOB',
    'pwa.description': 'Buka lebih cepat dari layar utama, beberapa halaman dapat memuat lebih cepat dari cache.',
    'pwa.note': 'Data langsung dan sebagian besar tindakan masih memerlukan koneksi internet.',
    'pwa.iosHint': 'Ketuk tombol bagikan, lalu pilih',
    'pwa.iosAction': '"Tambahkan ke Layar Utama"',
    'pwa.installLabel': 'Pasang BOB',
    'pwa.installButton': 'Pasang aplikasi',
  },
  hi: {
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.confirm': 'पुष्टि करें',
    'common.back': 'वापस',
    'common.baht': 'बाट',
    'common.percent': '%',
    'common.times': 'बार',
    'nav.feed': 'फ़ीड',
    'nav.groups': 'समूह',
    'nav.create': 'बनाएं',
    'nav.calendar': 'कैलेंडर',
    'nav.profile': 'प्रोफ़ाइल',
    'profile.title': 'प्रोफ़ाइल',
    'profile.yourBadges': 'आपके बैज',
    'profile.paidOnTime': 'समय पर भुगतान',
    'profile.debtClosed': 'ऋण बंद',
    'profile.newMember': 'नया सदस्य',
    'profile.totalAgreements': 'कुल समझौते',
    'profile.closedSuccess': 'पूर्ण',
    'profile.notifications': 'सूचनाएं',
    'profile.privacy': 'गोपनीयता',
    'profile.badges': 'बैज',
    'profile.history': 'इतिहास',
    'profile.help': 'सहायता',
    'profile.settings': 'सेटिंग्स',
    'profile.logout': 'लॉग आउट',
    'profile.logoutSuccess': 'लॉग आउट हो गया',
    'profile.featureInDev': 'विकास में सुविधा',
    'profile.language': 'भाषा',
    'profile.selectLanguage': 'भाषा चुनें',
    'friends.title': 'मित्र',
    'friends.count': 'मित्र',
    'friends.searchPlaceholder': 'मित्र खोजें...',
    'friends.noResults': 'कोई मित्र नहीं मिला',
    'friends.clearSearch': 'खोज साफ़ करें',
    'friends.noFriends': 'अभी तक कोई मित्र नहीं',
    'friends.addFirstHint': 'बिल साझा करने या समझौता बनाने के लिए मित्र जोड़ें',
    'friends.addFirst': 'पहला मित्र जोड़ें',
    'friends.addNew': 'नया मित्र जोड़ें',
    'friends.name': 'नाम',
    'friends.namePlaceholder': 'मित्र का नाम',
    'friends.phone': 'फ़ोन (वैकल्पिक)',
    'friends.phonePlaceholder': '08X-XXX-XXXX',
    'friends.add': 'मित्र जोड़ें',
    'friends.nameRequired': 'कृपया मित्र का नाम दर्ज करें',
    'friends.addSuccess': 'मित्र जोड़ा गया',
    'friends.deleteSuccess': 'मित्र हटाया गया',
    'friends.updateSuccess': 'मित्र अपडेट किया गया',
    'friends.deleteConfirmTitle': 'मित्र हटाएं?',
    'friends.deleteConfirmDesc': 'यह मौजूदा समझौतों या समूहों को प्रभावित नहीं करेगा',
    'friends.delete': 'हटाएं',
    'create.title': 'समझौता बनाएं',
    'create.youAre': 'आप हैं',
    'create.lender': 'उधारदाता',
    'create.borrower': 'उधारकर्ता',
    'create.friendInfo': 'मित्र जानकारी',
    'create.friendName': 'मित्र का नाम',
    'create.friendPhone': 'फ़ोन',
    'create.loanAmount': 'राशि',
    'create.interest': 'ब्याज',
    'create.interestRate': 'ब्याज दर',
    'create.noInterest': 'ब्याज नहीं',
    'create.flatRate': 'निश्चित दर',
    'create.effectiveRate': 'प्रभावी दर',
    'create.installments': 'किस्तें',
    'create.paymentFrequency': 'आवृत्ति',
    'create.daily': 'दैनिक',
    'create.weekly': 'साप्ताहिक',
    'create.monthly': 'मासिक',
    'create.dueDate': 'नियत तारीख',
    'create.notes': 'नोट्स',
    'create.paymentSummary': 'भुगतान सारांश',
    'create.principal': 'मूलधन',
    'create.interestPercent': '% ब्याज',
    'create.interestAmount': 'ब्याज राशि',
    'create.paymentCount': 'भुगतान संख्या',
    'create.submitRequest': 'अनुरोध भेजें',
    'create.calculationSummary': 'गणना सारांश',
    'create.totalInterest': 'कुल ब्याज',
    'create.perInstallment': 'प्रति किस्त',
    'create.compareAll': 'सभी की तुलना करें',
    'pwa.closeLabel': 'ऐप इंस्टॉल संकेत बंद करें',
    'pwa.title': 'BOB इंस्टॉल करें',
    'pwa.description': 'होम स्क्रीन से तेज़ी से खोलें, उपयोग के बाद कुछ पृष्ठ कैश से तेज़ लोड हो सकते हैं।',
    'pwa.note': 'लाइव डेटा और अधिकांश क्रियाओं के लिए अभी भी इंटरनेट कनेक्शन आवश्यक है।',
    'pwa.iosHint': 'शेयर बटन दबाएं, फिर चुनें',
    'pwa.iosAction': '"होम स्क्रीन में जोड़ें"',
    'pwa.installLabel': 'BOB इंस्टॉल करें',
    'pwa.installButton': 'ऐप इंस्टॉल करें',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof TranslationKeys) => string;
  currentLanguage: LanguageInfo;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'app-language';
const FALLBACK_LANGUAGE: Language = 'th';

function isLanguage(value: string | null): value is Language {
  return value !== null && languages.some((language) => language.code === value);
}

function detectBrowserLanguage(): Language | null {
  if (typeof navigator === 'undefined') {
    return null;
  }

  const candidates = [
    ...(navigator.languages || []),
    navigator.language,
  ].filter(Boolean) as string[];

  for (const candidate of candidates) {
    const normalized = candidate.toLowerCase().replace('_', '-');
    const exactMatch = languages.find((language) => language.code === normalized);
    if (exactMatch) {
      return exactMatch.code;
    }

    const baseLanguage = normalized.split('-')[0];
    const baseMatch = languages.find((language) => language.code === baseLanguage);
    if (baseMatch) {
      return baseMatch.code;
    }

    if (normalized.startsWith('zh')) {
      return 'zh';
    }
  }

  return null;
}

function getInitialLanguage(): Language {
  if (typeof window === 'undefined') {
    return FALLBACK_LANGUAGE;
  }

  const storedLanguage = localStorage.getItem(LANGUAGE_STORAGE_KEY);
  if (isLanguage(storedLanguage)) {
    return storedLanguage;
  }

  const browserLanguage = detectBrowserLanguage();
  if (browserLanguage) {
    return browserLanguage;
  }

  return FALLBACK_LANGUAGE;
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
  };

  const t = (key: keyof TranslationKeys): string => {
    return translations[language]?.[key] || translations[FALLBACK_LANGUAGE][key] || key;
  };

  const currentLanguage = languages.find((l) => l.code === language) || languages[0];

  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
