// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

function requireEnv(name: string, value: string | undefined): string {
  if (!value) {
    throw new Error(`Missing required env var: ${name}`);
  }

  return value;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const supabaseUrl = requireEnv("VITE_SUPABASE_URL", SUPABASE_URL);
const supabasePublishableKey = requireEnv("VITE_SUPABASE_PUBLISHABLE_KEY", SUPABASE_PUBLISHABLE_KEY);

// BUG-SEC-08 (trade-off acknowledged): Supabase stores the auth JWT in localStorage,
// which is accessible to any JavaScript running on the page and therefore an XSS
// exfiltration target. Moving to httpOnly cookies would require a custom auth proxy
// and is a significant architectural change. The accepted mitigation is a strict
// Content-Security-Policy (CSP) that prevents execution of injected scripts.
// Ensure the production server/CDN sets a CSP header disallowing inline scripts
// and restricting script-src to trusted origins only.
export const supabase = createClient<Database>(supabaseUrl, supabasePublishableKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
